
package stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConferenceService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8080/Conference/conference?wsdl")
public class ConferenceService
    extends Service
{

    private final static URL CONFERENCESERVICE_WSDL_LOCATION;
    private final static WebServiceException CONFERENCESERVICE_EXCEPTION;
    private final static QName CONFERENCESERVICE_QNAME = new QName("http://server/", "ConferenceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Conference/conference?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONFERENCESERVICE_WSDL_LOCATION = url;
        CONFERENCESERVICE_EXCEPTION = e;
    }

    public ConferenceService() {
        super(__getWsdlLocation(), CONFERENCESERVICE_QNAME);
    }

    public ConferenceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONFERENCESERVICE_QNAME, features);
    }

    public ConferenceService(URL wsdlLocation) {
        super(wsdlLocation, CONFERENCESERVICE_QNAME);
    }

    public ConferenceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONFERENCESERVICE_QNAME, features);
    }

    public ConferenceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConferenceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Conference
     */
    @WebEndpoint(name = "ConferencePort")
    public Conference getConferencePort() {
        return super.getPort(new QName("http://server/", "ConferencePort"), Conference.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Conference
     */
    @WebEndpoint(name = "ConferencePort")
    public Conference getConferencePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "ConferencePort"), Conference.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONFERENCESERVICE_EXCEPTION!= null) {
            throw CONFERENCESERVICE_EXCEPTION;
        }
        return CONFERENCESERVICE_WSDL_LOCATION;
    }

}
