
package stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ParticipantService", targetNamespace = "http://server/", wsdlLocation = "http://localhost:8080/Conference/participant?wsdl")
public class ParticipantService
    extends Service
{

    private final static URL PARTICIPANTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PARTICIPANTSERVICE_EXCEPTION;
    private final static QName PARTICIPANTSERVICE_QNAME = new QName("http://server/", "ParticipantService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Conference/participant?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PARTICIPANTSERVICE_WSDL_LOCATION = url;
        PARTICIPANTSERVICE_EXCEPTION = e;
    }

    public ParticipantService() {
        super(__getWsdlLocation(), PARTICIPANTSERVICE_QNAME);
    }

    public ParticipantService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PARTICIPANTSERVICE_QNAME, features);
    }

    public ParticipantService(URL wsdlLocation) {
        super(wsdlLocation, PARTICIPANTSERVICE_QNAME);
    }

    public ParticipantService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PARTICIPANTSERVICE_QNAME, features);
    }

    public ParticipantService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ParticipantService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Participant
     */
    @WebEndpoint(name = "ParticipantPort")
    public Participant getParticipantPort() {
        return super.getPort(new QName("http://server/", "ParticipantPort"), Participant.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Participant
     */
    @WebEndpoint(name = "ParticipantPort")
    public Participant getParticipantPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server/", "ParticipantPort"), Participant.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PARTICIPANTSERVICE_EXCEPTION!= null) {
            throw PARTICIPANTSERVICE_EXCEPTION;
        }
        return PARTICIPANTSERVICE_WSDL_LOCATION;
    }

}
